"""Parse Python .pyi stub files and SWIG-generated .py files into the intermediate representation."""

import ast
import logging
import re
from pathlib import Path

from .ir import IR, ClassDef, MethodDef, PropertyDef, EnumDef

logger = logging.getLogger(__name__)

NAMESPACE_MAP = {
    "core": "adsk.core",
    "fusion": "adsk.fusion",
    "cam": "adsk.cam",
}

# SWIG infrastructure classes to skip
SWIG_SKIP_CLASSES = {
    "_SwigNonDynamicMeta",
    "SwigPyIterator",
    "BoolVector",
    "DoubleVector",
    "FloatVector",
    "IntVector",
    "ShortVector",
    "StringVector",
    "UintVector",
    "EnsureGILState",
}

# SWIG infrastructure methods to skip
SWIG_SKIP_METHODS = {
    "__init__",
    "__repr__",
    "__deref__",
    "__eq__",
    "__ne__",
    "__swig_destroy__",
}


def parse_stubs(stubs_path: str) -> IR:
    """Parse all .pyi and .py files under stubs_path into an IR."""
    ir = IR()
    stubs_dir = Path(stubs_path)

    # Collect files to parse: prefer .pyi over .py if both exist
    files_to_parse = {}  # stem -> path

    for py_file in sorted(stubs_dir.glob("*.py")):
        stem = py_file.stem
        if stem == "__init__" or stem.startswith("_"):
            continue
        files_to_parse[stem] = py_file

    # .pyi files override .py files
    for pyi_file in sorted(stubs_dir.glob("*.pyi")):
        stem = pyi_file.stem
        if stem == "__init__":
            continue
        files_to_parse[stem] = pyi_file

    for stem, path in sorted(files_to_parse.items()):
        namespace = NAMESPACE_MAP.get(stem, f"adsk.{stem}")
        logger.info(f"Parsing {path.name} as {namespace}")
        _parse_file(path, namespace, ir)

    # Also check for subdirectory layout (e.g. core/__init__.pyi)
    for subdir in sorted(stubs_dir.iterdir()):
        if subdir.is_dir() and subdir.name in NAMESPACE_MAP:
            init_pyi = subdir / "__init__.pyi"
            if init_pyi.exists():
                namespace = NAMESPACE_MAP[subdir.name]
                _parse_file(init_pyi, namespace, ir)

    return ir


def _is_swig_file(tree: ast.Module) -> bool:
    """Detect if a file is SWIG-generated by looking for SWIG infrastructure."""
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and node.name == "_SwigNonDynamicMeta":
            return True
        # Check for _swig_repr function
        if isinstance(node, ast.FunctionDef) and node.name == "_swig_repr":
            return True
    return False


def _parse_file(path: Path, namespace: str, ir: IR):
    source = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        logger.warning(f"Failed to parse {path}: {e}")
        return

    is_swig = _is_swig_file(tree)

    if is_swig:
        _parse_swig_file(tree, source, namespace, ir)
    else:
        _parse_pyi_file(tree, namespace, ir)


def _parse_pyi_file(tree: ast.Module, namespace: str, ir: IR):
    """Parse a .pyi stub file (original path)."""
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            if _is_enum_class(node):
                ir.add_enum(_parse_enum(node, namespace))
            else:
                ir.add_class(_parse_class(node, namespace))


def _parse_swig_file(tree: ast.Module, source: str, namespace: str, ir: IR):
    """Parse a SWIG-generated .py file."""
    # First pass: collect all classes and their _get_ methods
    class_nodes = {}  # name -> ast.ClassDef
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            class_nodes[node.name] = node

    # Second pass: collect module-level property assignments
    # Pattern: ClassName.propName = property(ClassName._get_propName, ...)
    property_assignments = {}  # class_name -> {prop_name -> (getter_name, setter_name, doc)}
    _collect_property_assignments(tree, property_assignments)

    # Process each class
    for name, node in class_nodes.items():
        if _should_skip_swig_class(name):
            continue

        if _is_swig_enum_class(node):
            enum = _parse_swig_enum(node, namespace)
            if enum and enum.values:
                ir.add_enum(enum)
        else:
            cls = _parse_swig_class(node, namespace, property_assignments.get(name, {}))
            ir.add_class(cls)


def _should_skip_swig_class(name: str) -> bool:
    """Check if a class should be skipped (SWIG infrastructure)."""
    if name in SWIG_SKIP_CLASSES:
        return True
    if name.startswith("_Swig"):
        return True
    return False


def _collect_property_assignments(tree: ast.Module, result: dict):
    """Collect module-level property assignments like ClassName.prop = property(...)."""
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.Assign):
            continue
        if len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Attribute):
            continue
        if not isinstance(target.value, ast.Name):
            continue

        class_name = target.value.id
        prop_name = target.attr

        # Skip infrastructure
        if prop_name in ("thisown", "cast"):
            continue

        # Check if the value is a property() call
        if not isinstance(node.value, ast.Call):
            continue
        func = node.value.func
        if not (isinstance(func, ast.Name) and func.id == "property"):
            continue

        # Extract getter, setter, doc from property() call
        args = node.value.args
        keywords = {kw.arg: kw for kw in node.value.keywords}

        getter_name = None
        setter_name = None
        doc = ""

        if len(args) >= 1:
            getter_name = _attr_chain(args[0])
        if len(args) >= 2:
            setter_name = _attr_chain(args[1])

        if "doc" in keywords:
            doc_node = keywords["doc"].value
            if isinstance(doc_node, ast.Constant) and isinstance(doc_node.value, str):
                doc = doc_node.value

        if class_name not in result:
            result[class_name] = {}
        result[class_name][prop_name] = (getter_name, setter_name, doc)


def _attr_chain(node) -> str | None:
    """Extract dotted name from an AST node like ClassName._get_x."""
    if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name):
        return f"{node.value.id}.{node.attr}"
    if isinstance(node, ast.Name):
        return node.id
    return None


def _is_swig_enum_class(node: ast.ClassDef) -> bool:
    """Detect enum classes in SWIG files.

    Enum classes have value assignments (not starting with _) but no _get_* methods.
    """
    has_value_assignments = False
    has_get_methods = False

    for item in node.body:
        if isinstance(item, ast.FunctionDef):
            if item.name.startswith("_get_"):
                has_get_methods = True
            # Regular public methods (not dunder, not _get/_set) indicate a real class
            if (not item.name.startswith("_")
                    and item.name not in ("classType",)):
                return False
        elif isinstance(item, ast.Assign):
            for target in item.targets:
                if isinstance(target, ast.Name):
                    name = target.id
                    if (not name.startswith("_")
                            and name != "thisown"
                            and name not in ("__repr__",)):
                        has_value_assignments = True

    return has_value_assignments and not has_get_methods


def _parse_swig_enum(node: ast.ClassDef, namespace: str) -> EnumDef:
    """Parse a SWIG enum class."""
    values = []
    description = _extract_class_docstring(node)

    for item in node.body:
        if isinstance(item, ast.Assign):
            for target in item.targets:
                if isinstance(target, ast.Name):
                    name = target.id
                    if (not name.startswith("_")
                            and name != "thisown"
                            and name not in ("__repr__",)):
                        values.append(name)

    return EnumDef(name=node.name, namespace=namespace, values=values,
                   description=description)


def _parse_swig_class(node: ast.ClassDef, namespace: str,
                       prop_assignments: dict) -> ClassDef:
    """Parse a SWIG class definition."""
    parent = _extract_parent(node)
    # Skip 'object' as parent -- it's the Python default, not a real API parent
    if parent == "object":
        parent = ""
    description = _extract_class_docstring(node)
    properties = {}
    methods = {}
    is_collection = False

    # Collect _get_ methods for type info
    getter_types = {}  # e.g. "_get_x" -> "float"
    for item in node.body:
        if isinstance(item, ast.FunctionDef) and item.name.startswith("_get_"):
            ret_type = _annotation_to_str(item.returns) if item.returns else ""
            getter_types[item.name] = ret_type

    # Build properties from module-level property assignments
    for prop_name, (getter_name, setter_name, doc) in prop_assignments.items():
        # Get type from the _get_ method return annotation
        get_method = f"_get_{prop_name}"
        prop_type = getter_types.get(get_method, "")
        read_only = setter_name is None
        properties[prop_name] = PropertyDef(
            name=prop_name, type=prop_type, read_only=read_only,
            description=doc,
        )

    # Parse public methods (skip _get_, _set_, dunder, infrastructure)
    for item in node.body:
        if not isinstance(item, ast.FunctionDef):
            continue
        name = item.name
        # Skip property implementation methods
        if name.startswith("_get_") or name.startswith("_set_"):
            continue
        # Skip dunder methods and other private methods
        if name.startswith("_"):
            continue
        # Skip classType -- it's SWIG infrastructure
        if name == "classType":
            continue

        method = _parse_swig_method(item)
        if method:
            methods[method.name] = method
            if method.name == "item" and method.returns:
                is_collection = True

    cls = ClassDef(
        name=node.name, namespace=namespace, parent=parent,
        description=description,
        properties=properties, methods=methods, is_collection=is_collection,
    )
    if is_collection and "item" in methods:
        cls.collection_item_type = methods["item"].returns
    return cls


def _extract_class_docstring(node: ast.ClassDef) -> str:
    """Extract docstring from a class node."""
    if (node.body
            and isinstance(node.body[0], ast.Expr)
            and isinstance(node.body[0].value, ast.Constant)
            and isinstance(node.body[0].value.value, str)):
        return node.body[0].value.value.strip()
    return ""


def _parse_swig_method(node: ast.FunctionDef) -> MethodDef | None:
    """Parse a method from a SWIG class."""
    is_static = any(isinstance(d, ast.Name) and d.id == "staticmethod"
                     for d in node.decorator_list)
    args = []
    for arg in node.args.args:
        if arg.arg == "self":
            continue
        arg_type = _annotation_to_str(arg.annotation) if arg.annotation else ""
        args.append((arg.arg, arg_type))

    return_type = _annotation_to_str(node.returns) if node.returns else ""
    description = _extract_method_docstring(node)

    return MethodDef(name=node.name, args=args, returns=return_type,
                     static=is_static, description=description)


def _extract_method_docstring(node: ast.FunctionDef) -> str:
    """Extract docstring from a method node."""
    if (node.body
            and isinstance(node.body[0], ast.Expr)
            and isinstance(node.body[0].value, ast.Constant)
            and isinstance(node.body[0].value.value, str)):
        return node.body[0].value.value.strip()
    return ""


# --- Original .pyi parsing functions (unchanged) ---

def _is_enum_class(node: ast.ClassDef) -> bool:
    has_assignments = False
    has_methods = False
    for item in node.body:
        if isinstance(item, (ast.Assign, ast.AnnAssign)):
            has_assignments = True
        if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
            has_methods = True
    return has_assignments and not has_methods


def _parse_enum(node: ast.ClassDef, namespace: str) -> EnumDef:
    values = []
    for item in node.body:
        if isinstance(item, ast.Assign):
            for target in item.targets:
                if isinstance(target, ast.Name):
                    values.append(target.id)
        elif isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
            values.append(item.target.id)
    return EnumDef(name=node.name, namespace=namespace, values=values)


def _parse_class(node: ast.ClassDef, namespace: str) -> ClassDef:
    parent = _extract_parent(node)
    properties = {}
    methods = {}
    is_collection = False

    for item in node.body:
        if isinstance(item, ast.FunctionDef):
            if _is_property(item):
                prop = _parse_property(item)
                if prop:
                    properties[prop.name] = prop
            elif item.name.startswith("_") and item.name != "__init__":
                continue
            else:
                method = _parse_method(item)
                if method:
                    methods[method.name] = method
                    if method.name == "item" and method.returns:
                        is_collection = True

    cls = ClassDef(
        name=node.name, namespace=namespace, parent=parent,
        properties=properties, methods=methods, is_collection=is_collection,
    )
    if is_collection and "item" in methods:
        cls.collection_item_type = methods["item"].returns
    return cls


def _extract_parent(node: ast.ClassDef) -> str:
    if not node.bases:
        return ""
    base = node.bases[0]
    if isinstance(base, ast.Name):
        return base.id
    if isinstance(base, ast.Attribute):
        return base.attr
    return ""


def _is_property(node: ast.FunctionDef) -> bool:
    return any(
        (isinstance(d, ast.Name) and d.id == "property")
        or (isinstance(d, ast.Attribute) and d.attr in ("getter", "setter"))
        for d in node.decorator_list
    )


def _is_setter(node: ast.FunctionDef) -> bool:
    return any(isinstance(d, ast.Attribute) and d.attr == "setter" for d in node.decorator_list)


def _parse_property(node: ast.FunctionDef) -> PropertyDef | None:
    if _is_setter(node):
        return None
    return_type = _annotation_to_str(node.returns) if node.returns else ""
    return PropertyDef(name=node.name, type=return_type, read_only=True)


def _parse_method(node: ast.FunctionDef) -> MethodDef | None:
    is_static = any(isinstance(d, ast.Name) and d.id == "staticmethod" for d in node.decorator_list)
    args = []
    for arg in node.args.args:
        if arg.arg == "self":
            continue
        arg_type = _annotation_to_str(arg.annotation) if arg.annotation else ""
        args.append((arg.arg, arg_type))
    return_type = _annotation_to_str(node.returns) if node.returns else ""
    return MethodDef(name=node.name, args=args, returns=return_type, static=is_static)


def _annotation_to_str(node) -> str:
    if node is None:
        return ""
    if isinstance(node, ast.Constant):
        v = str(node.value)
        # Handle SWIG string annotations like "adsk.core.Point3D" -> strip namespace
        if "." in v:
            return v.rsplit(".", 1)[-1]
        # Handle SWIG pointer types like "adsk.core.Point3D *"
        v = v.rstrip(" *&")
        if "." in v:
            return v.rsplit(".", 1)[-1]
        return v
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    if isinstance(node, ast.Subscript):
        base = _annotation_to_str(node.value)
        inner = _annotation_to_str(node.slice)
        return f"{base}[{inner}]"
    return ast.dump(node)
